Claim handling and complex mapping rules
nextcloud/user_oidc pull request #317
Opened 2021-08-31 18:35 UTC by tsdicloud

This pull request contains an extension that has been needed to integrate with a big, corporate identity management system.

## Part 1: Support OpenId connect claims
OpenID connect claims define a set of attributes that is passes together with the token back to the client that is requesting authorisation. A client can select the attribute sets in its request to IDM by listing attribute profile names in`scope` field 
The `scope` field is added to the Provider configuration and defaults to `openid email profile'

## Part 2: Complex mapping rules coded with events
Before a field in user account is filled with the mapped field in the token, the value of the token is published as `AttributeMappedEvent`. The event contains all claims as event payload, as well as the value of the mapped source claim in token. If the mapped claim does not exist in token, the `null` value is set as default in event.

The `AttributeMappedEvent::handle(Event $event)` can implement complex code for rules based on multiple claims and pass back the result by `setValue`. With using the event system, the rules can be implemented in a separate app which decouples business rule logic from `user_oidc` technical code.

If the value of an event is `null`and there is no directly mapped field value available, the field in user account is not set.

## Part 3: query parameters for discovered `token_endpoint`
For some developers, it is tempting to extend functionality of the IDM `token_endpoint` by introducing custom query parameter. This is not good for a standard OpenID connect client implementation, as the `token_endpoint` is called as a second step after `discovery` of the OPenId connect endpoints. To support such query parameters and not implement a `custom`case for it. the `discovery_url` can be configured in provider with query parameters. The query is send with the discover AND with the token endpoint. This usually works well because custom query parameter can usually be send to discovery endpoint but are ignored there. After discovery, the same query parameters are again send to `token_endpoint`and accepted there.

2021-09-03 10:12 UTC, juliushaertl commented
> TypeError: Argument 5 passed to OCA\UserOIDC\Db\ProviderMapper::createOrUpdateProvider() must be of the type string, null given, called in /home/runner/work/user_oidc/user_oidc/apps/user_oidc/lib/Command/UpsertProvider.php on line 128 and defined in /home/runner/work/user_oidc/user_oidc/apps/user_oidc/lib/Db/ProviderMapper.php:99

```
 There was 1 failure:

1) ProviderServiceTest::testGetProvidersWithSettings
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         'clientId' => null
         'discoveryEndpoint' => null
         'settings' => Array (...)
+        'scope' => null
     )
     1 => Array (
         'id' => 2
@@ @@
         'clientId' => null
         'discoveryEndpoint' => null
         'settings' => Array (...)
+        'scope' => null
     )
 )

/home/runner/work/user_oidc/user_oidc/apps/user_oidc/tests/unit/Service/ProviderServiceTest.php:98
```

2021-09-07 14:17 UTC, juliushaertl approved these changes

2021-09-07 16:31 UTC, eneiluj requested changes
Looking good!
A few details to adjust and we're good to go.
Thanks a lot for this PR.

2021-09-07 16:31 UTC, eneiluj commented on README.md
> +npm install npm
```suggestion
npm ci
```

2021-09-07 16:31 UTC, eneiluj commented on appinfo/info.xml
> +	<summary>Use an OpenID Connect backed to login to your Nextcloud</summary>
```suggestion
	<summary>Use an OpenID Connect backend to login to your Nextcloud</summary>
```

2021-09-07 16:31 UTC, eneiluj commented on appinfo/info.xml
> +	<description>Allows felxible configuration of an OIDC server as Nextcloud login user backend.</description>
```suggestion
	<description>Allows flexible configuration of an OIDC server as Nextcloud login user backend.</description>
```

2021-09-07 16:31 UTC, eneiluj commented on lib/Db/Provider.php
> + * @method void setCustomQuery(string $customQuery)
```suggestion
```
I guess this was forgotten here.

2021-09-07 16:31 UTC, eneiluj commented on src/components/SettingsForm.vue
> +			<label for="oidc-scopr">{{ t('user_oidc', 'Scope') }}</label>
```suggestion
			<label for="oidc-scope">{{ t('user_oidc', 'Scope') }}</label>
```

2021-09-10 07:54 UTC, eneiluj approved these changes

2021-09-10 07:54 UTC, merged