Add client_id and id_token_hint to IdP logout
nextcloud/user_oidc pull request #493
Opened 2022-08-26 17:39 UTC by ubipo

This adds two parameters to the end_session_endpoint IdP URL which the
user gets redirected to when singleLogout is triggered.

These paramters are:
- client_id: the client ID of the current session's provider
- id_token_hint: the raw id_token that was obtained during the code
  callback of this session's login flow (set in session variable `oidc.id_token`).

Some providers (e.g. node-oidc-provider and Keycloak) require this when using the code OAuth flow.

Because passing id_token_hint reveals the id_token to the user agent, a
app setting was also added to optionally turn this behaviour off (default is
turned on, see image below).

Builds upon PR #373 / issue #336
Fixes issue #449

![image](https://user-images.githubusercontent.com/11903688/186961018-9ec7a16f-b56b-42c9-bea8-a7a231241344.png)

Signed-off-by: Pieter Fiers <pieter@pfiers.net>

2022-08-31 16:14 UTC, eneiluj requested changes
Nice! Thanks for the PR. Nicely done.

I had trouble finding doc about why the client_id is needed but here it is: https://www.keycloak.org/docs/latest/release_notes/index.html#oidc-logout-changes

Could you sign your commits and rebase your branch on this project's master?

2022-08-31 16:14 UTC, eneiluj commented on lib/Service/ProviderService.php
> +	);
```suggestion
	private const BOOLEAN_SETTINGS = [
		self::SETTING_UNIQUE_UID,
		self::SETTING_CHECK_BEARER,
		self::SETTING_SEND_ID_TOKEN_HINT,
	];
```

2022-08-31 16:14 UTC, eneiluj commented on src/components/SettingsForm.vue
> +			{{ t('user_oidc', 'Should the ID token be included as a parameter (id_token_hint) of the provider\'s logout URL? The user will be redirected to this URL after logout in Nextcloud. Enabling this ex
```suggestion
			{{ t('user_oidc', 'Should the ID token be included as a the id_token_hint GET parameter in the OpenID logout URL? User are redirected to this URL after logging out of Nextcloud. Enabling this setting exposes the OIDC ID token to the user agent, which may not be necessary depending on the OIDC provider.') }}
```

2022-09-01 10:41 UTC, ubipo commented
Thanks for the review! I've implemented the suggestions, rebased onto master, signed the commit, and added some more info on the use of the parameters. Should be good to go :)

2022-09-02 10:54 UTC, eneiluj approved these changes
:+1:

2022-09-02 10:54 UTC, merged