Fix/661/additional attributes
nextcloud/user_oidc pull request #729
Opened 2023-12-07 14:20 UTC by nc-fkl

- Added multiple attributes
- Aligned mapping
- Aligned frontend layout a littlebit so that its more categorized
- Setting newly added properties of account via IAccountManager instead of IUser

2023-12-07 15:30 UTC, julien-nc requested changes
Nice!
Unit and integration tests don't pass.
I'll make real life tests when they do.

2023-12-07 15:49 UTC, nc-fkl commented on lib/Service/ProvisioningService.php
> +		$backendUser = $this->userMapper->getOrCreate($providerId, (string)$event->getValue());
Actualy my ide marked it as error that's not casted, that was the only reason for that :) took your solution now

2023-12-07 15:51 UTC, nc-fkl commented on lib/Service/ProvisioningService.php
> +		$address = preg_replace('/^, |, $/', '', str_replace('  ', ' ', implode(', ', $addressParts)));
Ah good point, makes sense, so lets keep the "ugly" string when a value was not provided, will also be a good hint for the user/admin itself that a value isn't set correctly.

2023-12-08 14:55 UTC, julien-nc requested changes
Check the unit tests output. They need to be adjusted with the new setting values.

2023-12-08 14:55 UTC, julien-nc commented on lib/Command/UpsertProvider.php
> +		}
You forgot to add this option in the configure method. This will make the integration tests pass.

2023-12-13 16:01 UTC, julien-nc requested changes
Nice, i tried with a few attributes, works like a charm.

It would be nice to hide all those setting fields and make them appear/disappear if user clicks on a "Extra  attributes mapping" button.

Also, now there are conflicts with main. Nothing weird, the new options in the UpSert command are added on the same line. Let me know if you need help to solve the conflicts.

2023-12-18 12:59 UTC, nc-fkl commented
> Nice, i tried with a few attributes, works like a charm.
> 
> It would be nice to hide all those setting fields and make them appear/disappear if user clicks on a "Extra attributes mapping" button.
> 
> Also, now there are conflicts with main. Nothing weird, the new options in the UpSert command are added on the same line. Let me know if you need help to solve the conflicts.

Redbased and added expandable/collapsable extra attributes. Would be nice if you can review again 🏓 , thank you @julien-nc :)

2023-12-18 13:06 UTC, julien-nc approved these changes
Woop woop

2023-12-18 13:11 UTC, merged