Implement soft auto provisioning
nextcloud/user_oidc pull request #730
Opened 2023-12-08 12:21 UTC by julien-nc

Problem: When auto provisioning is enabled, if a user with the same ID exists in another backend (Db, LDAP...), we create a second user in the user_oidc backend which leads to issues and confusion.

Here is a partial solution to this problem:
New config `soft_auto_provision` flag (enabled by default).
* When enabled
    * If the user already exists in another backend, we don't create a new one in our backend. We update the information (mapped attributes) of the existing user.
    * If the user does not exist in another backend, we create it in ours
* When disabled
    * We refuse login of users that already exist in other backends

This does not migrate existing users to the user_oidc backend but allows them to log in without creating a duplicate user.

Nothing was changed when auto provisioning is disabled.

Extra change: In the user backend, the ldap sync was not triggered when looking for an existing user.

2023-12-08 13:40 UTC, nc-fkl commented on lib/Service/ProvisioningService.php
> +				$user->setDisplayName($newDisplayName);
Not sure here if the $newDisplayName in L112 is always set as its only set once when the if condition in L101 was triggered

2023-12-08 14:15 UTC, nc-fkl requested changes
Please check my comment regarding $newDisplayName in ProvisioningService.php

2023-12-08 14:28 UTC, nc-fkl approved these changes
Nice! :)

2024-01-23 09:34 UTC, julien-nc commented
@juliushaertl Could you check if this PR makes sense? :grin:

2024-01-31 07:16 UTC, juliushaertl approved these changes
The approach looks good to me, haven't tested though 👍

2024-02-23 10:15 UTC, merged

2024-02-28 16:04 UTC, brtptrs commented
Would it be possible to catch this Problem during while doing this provisioning?
https://github.com/nextcloud/user_oidc/issues/656
Maybe with a config flag to enable a lowercase - uppercase verification