feat: restrict login to users matching a certain group
nextcloud/user_oidc pull request #884
Opened 2024-06-17 14:29 UTC by bergerar

Fixes  #867

2024-10-21 15:11 UTC, edward-ly commented
Closing as discussed in https://github.com/nextcloud/user_oidc/issues/867#issuecomment-2406113586.

2024-10-21 16:26 UTC, Stefanqn commented
I'm quite surprised about this decision: the referenced discussion describes a cumbersome workaround, including creating custom Keycloak flows and carefully adding the Keycloak plugin to multiple locations in these flows. Furthermore, it's an unofficial, single-developer plugin and it limits the solution space to Keycloak. On the other hand, a pull request with a proper solution at PEP (Policy Enforcement Point) exists and gets rejected. Would you please elaborate on this decision?

2024-10-21 19:23 UTC, edward-ly commented
We happily welcome open discussion from anyone, not just those already mentioned. We're not saying that this feature isn't useful, but rather that it's better to implement it as a separate app or use LDAP as an alternative.

I agree that the Keycloak extension isn't a perfect solution, but what about my point above? What does this PR provide that another app doesn't (user_ldap or otherwise)?

2024-10-24 09:57 UTC, Stefanqn commented
Thank you Edward for keeping an open mind on this. 

Regarding your point(s):
a)  use LDAP as an alternative: I'm quite confused about this suggestion as it would result in switching to a completely different protocol for authorization - one many don't have in place. Maybe you can describe your idea in more detail.
b)  implement it as a separate app: what would be the motivation to do so? You mentioned user_LDAP directly implementing this, so why do it differently for user_oidc?

2024-10-24 15:45 UTC, edward-ly commented
Let's continue the discussion in https://github.com/nextcloud/user_oidc/issues/867#issuecomment-2435647720 in which I made a response there.

2024-10-25 16:29 UTC, edward-ly commented
Reopening as per https://github.com/nextcloud/user_oidc/issues/867#issuecomment-2438267667, will test and merge within the next few days.

2024-10-28 18:32 UTC, edward-ly requested changes
Please rebase the branch to start at the latest (main) commit and resolve any conflicts before we can start testing and merging, thank you.

2024-10-29 21:51 UTC, bergerar commented
I rebased the pull request, unit tests and lints are passing and I did some manual tests in my setup of the feature.

2024-10-31 12:54 UTC, julien-nc requested changes
Looks sane to me. Tested, works fine :heavy_check_mark: 

A small improvement could be to check if the leading and trailing slashes are there and add them if not.

The labels/hints in the settings need to be as much descriptive as possible. See inline comments.

2024-10-31 12:54 UTC, julien-nc commented on lib/Controller/LoginController.php
> +				$message = $this->l10n->t('You do not have permission to log in to this instance. If you believe this is an error, please contact an Administrator.');
```suggestion
				$message = $this->l10n->t('You do not have permission to log in to this instance. If you think this is an error, please contact an administrator.');
```

2024-10-31 12:54 UTC, julien-nc commented on lib/Controller/LoginController.php
> +				return $this->build403TemplateResponse($message, Http::STATUS_FORBIDDEN, ['reason' => 'user not allowed to login']);
```suggestion
				return $this->build403TemplateResponse($message, Http::STATUS_FORBIDDEN, ['reason' => 'user not in any whitelisted group']);
```

2024-10-31 12:54 UTC, julien-nc commented on src/components/SettingsForm.vue
> +			{{ t('user_oidc', 'Only groups matching the whitelist regex will be created, updated and deleted by the group claim') }}
```suggestion
			{{ t('user_oidc', 'Only groups matching the whitelist regex will be created, updated and deleted by the group claim. For example: {regex} allows all groups which ID starts with {substr}', { regex: '/^blue/', substr: 'blue' }) }}
```
Or anything more descriptive.

2024-10-31 12:54 UTC, julien-nc commented on src/components/SettingsForm.vue
> +			{{ t('user_oidc', 'Restrict login for users without whitelisted groups.') }}
```suggestion
			{{ t('user_oidc', 'Restrict login for users that are not in any whitelisted group') }}
```

2024-10-31 12:54 UTC, julien-nc commented on src/components/SettingsForm.vue
> +			{{ t('user_oidc', 'Users that are not part of a whitelisted group are not created and can not login') }}
```suggestion
			{{ t('user_oidc', 'Users that are not part of any whitelisted group are not created and can not login') }}
```

2024-11-12 20:48 UTC, bergerar commented
@julien-nc  the delimiters are now added automatically if the first one is missing.

There was one check failing, but it was the same one as on the main branch (Integration tests / php8.1-mysql-stable27)

2024-11-13 19:50 UTC, bergerar commented
still had an old version of the php-cs-fixer.

I did now rebase, update install the updated dependencies and run `composer run cs:fix`.

@julien-nc is should now pass all tests

2024-11-14 00:23 UTC, julien-nc approved these changes

2024-11-14 00:23 UTC, merged

2024-11-16 12:30 UTC, bergerar commented
Thanks for merging and your work in general on open source. @julien-nc

2024-11-18 10:30 UTC, julien-nc commented
@bergerar Thank you for your patience, your perseverance, your nice words and your contribution!